# Generated by Django 3.1.5 on 2021-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学部ID')),
                ('name', models.CharField(max_length=10, verbose_name='学部名')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
