# Generated by Django 3.1.1 on 2021-01-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='faculty_id',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
